source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Rails
gem 'rails', '~> 5.1.4'

# Postgresql
gem 'pg', '~> 0.18'

# Puma server
gem 'puma', '~> 3.7'

# Authentication
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'

# Rest Api docs
gem 'swagger-docs'
gem 'apipie-rails'

group :development, :test do
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
